### ISSUE TITLE
The parameter (classes: [list] default = None) in YolactInference and Yolov8Inference is not more used

### ISSUE THREAD

**Issue by andreazuna89** [IASRobolab/ai_utils#16]
I think the parameter classes is not more passed to the function img_inference of the two classes but it is used in the initialization through classes_white_list parameter. If yes, we need to update the setup of both the YolactInference and Yolov8Inference docs.

**Comment by FedericoRollo** [comment]
I don't think to have understood the question. 
The class_white_list parameter is initialized in the DetectorInterface class from which yolact and yolo inherit. 
It is managed in that phase and the son classes derive their methods.
There is no parameter class used in img_inference and other parts. 

@andreazuna89 if you want to clarify my misunderstanding please provide a code example by linking the code in the issue.

**Comment by FedericoRollo** [comment]
Ok I removed the typos from the documentations!
