### ISSUE TITLE
Installation of tracking repo

### ISSUE THREAD

**Issue by andreazuna89** [IASRobolab/ai_utils#19]
We need to create an installation setup for the tracking repository https://github.com/mikel-brostrom/yolov8_tracking and then modify some initial import lines in Yolov8InferTrack.py.

**Comment by FedericoRollo** [comment]
I forked the work, which you can find in [yolov8_tracking](https://github.com/IASRobolab/yolov8_tracking).

The installer of yolov8 is already provided so you just need to go in ```your_path/yolov8_tracking/yolov8``` on the terminal and type the usual ```pip install -e  .```. If you do that probably you will need to remove all the yolov8 from the imports in ```Yolov8InferTrack.py``` and leave them starting directly from ```ultralytics```. 
Note that this installation will overwrite other previous installations of ultralytics (e.g. the ones you made to run yolov8 standard)

Regarding the installation of the trackers, I made the installer but it needs to be tested. The installation procedure is the usual also in this case; open the terminal, go in ```your_path/yolov8_tracking/trackers``  and then ```pip install -e  .```. 

Remember to remove https://github.com/IASRobolab/ai_utils/blob/master/ai_utils/detectors/Yolov8InferTrack.py#L45-L48 before testing.
If it will work you can close the issue!

**Comment by FedericoRollo** [comment]
It works now
